version: "3.4"
services:
  ayro-prerender:
    << : *common
    image: "ayro-prerender:latest"
    container_name: "ayro-prerender"
    hostname: "ayro-prerender"
    volumes:
      - "${AYRO_HOME}/configs/ayro-prerender.properties:/usr/src/ayro-prerender/config.properties"
    networks:
      default:
        ipv4_address: "172.28.5.4"