version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - "/opt/applications/chatz-configs/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "/opt/applications/chatz-configs/nginx:/opt/applications/chatz-configs/nginx"
    ports:
      - "80:80"
      - "443:443"
      - "3101:3101"