version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: "ayro-nginx"
    volumes:
      - "/opt/applications/ayro-configs/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "/opt/applications/ayro-configs/nginx:/opt/applications/ayro-configs/nginx"
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases:
          - "ayro-nginx"
networks:
  default:
    external:
      name: "ayro-network"